{
 "title": "Dashboard",
 "time": { "from": "2023-10-26T14:07:27.713Z", "to": "2023-10-26T14:07:42.244Z" },
 "templating": {
  "list": [
   {
    "name": "req_type",
    "query": "SHOW TAG VALUES WITH KEY = \"req_type\""
   },
   {
    "name": "origin",
    "query": "SHOW TAG VALUES WITH KEY = \"origin\""
   },
   {
    "name": "request",
    "query": "SHOW TAG VALUES WITH KEY = \"request\""
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "request" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "query": "SELECT distinct(\"value\") \nFROM \"http_req_duration\" \nWHERE \n    (\n        (\"req_type\" = 'All' OR \"req_type\" =~ /^$req_type$/) \n        AND \n        (\"origin\" = 'All' OR \"origin\" =~ /^$origin$/)\n        AND \n        (\"request\" = 'All' OR \"request\" =~ /^$request$/)\n    ) \n    AND \n    $timeFilter \nGROUP BY time($__interval), \"request\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max. Request Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT distinct(\"value\") \nFROM \"http_req_duration\" \nWHERE \n        (\n        (\"req_type\" = 'All' OR \"req_type\" =~ /^$req_type$/) \n        AND \n        (\"origin\" = 'All' OR \"origin\" =~ /^$origin$/)\n        AND \n        (\"request\" = 'All' OR \"request\" =~ /^$request$/)\n    ) \n    AND \n    $timeFilter \nGROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Avg. Request Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Avg. Request Duration",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT distinct(\"value\") \nFROM \"http_req_duration\" \nWHERE \n        (\n        (\"req_type\" = 'All' OR \"req_type\" =~ /^$req_type$/) \n        AND \n        (\"origin\" = 'All' OR \"origin\" =~ /^$origin$/)\n        AND \n        (\"request\" = 'All' OR \"request\" =~ /^$request$/)\n    ) \n    AND \n    $timeFilter \nGROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Min. Request Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "alias": "Max. Request Duration",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT distinct(\"value\") \nFROM \"http_req_duration\" \nWHERE \n       (\n        (\"req_type\" = 'All' OR \"req_type\" =~ /^$req_type$/) \n        AND \n        (\"origin\" = 'All' OR \"origin\" =~ /^$origin$/)\n        AND \n        (\"request\" = 'All' OR \"request\" =~ /^$request$/)\n    ) \n    AND \n    $timeFilter \nGROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "http_req_failed (%)",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 15, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Request Duration",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_failed",
     "query": "SELECT mean(\"value\") FROM \"http_req_failed\" WHERE     (\n        (\"req_type\" = 'All' OR \"req_type\" =~ /^$req_type$/) \n        AND \n        (\"origin\" = 'All' OR \"origin\" =~ /^$origin$/)\n        AND \n        (\"request\" = 'All' OR \"request\" =~ /^$request$/)\n    )  AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "req_type", "operator": "=~", "value": "/^$req_type$/" }
     ]
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "Request Duration",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "query": "SELECT distinct(\"value\") \nFROM \"http_req_duration\" \nWHERE \n    (\n        (\"req_type\" = 'All' OR \"req_type\" =~ /^$req_type$/) \n        AND \n        (\"origin\" = 'All' OR \"origin\" =~ /^$origin$/)\n        AND \n        (\"request\" = 'All' OR \"request\" =~ /^$request$/)\n    ) \n    AND \n    $timeFilter \nGROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "req_type", "operator": "=~", "value": "/^$req_type$/" }
     ]
    }
   ]
  }
 ]
}